### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by coltmort** [coltmort/cuddly-palm-tree#1]
- [x] update / delete posts
- [x] after adding post, pass logged
- [x] after adding post, redirect to dashboard
- [x] after idle log out user
- [x] post focus only if logged in, else redirect to login/signup
- [x] check comment only if signed in
- [x] only able to delete own comments
- [ ] Heroku
